### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by andrew222651** [matangover/mypyls#5] opened 2020-09-08 17:59 UTC
before running
```
~/.mypyls/bin/pip install "https://github.com/matangover/mypyls/archive/master.zip#egg=mypyls[default-mypy]"
```
I have to run ```~/.mypyls/bin/pip install wheel```
or there is an error

**Comment by matangover** [comment] 2020-09-08 18:51
Thanks! I actually already got this [issue](https://github.com/matangover/mypy-vscode/issues/11) on the other repo but I couldn't reproduce it  :\ I should try again. Are you also on Fedora?

**Comment by andrew222651** [comment] 2020-09-08 19:03
Oh that's weird. Well I'm on Ubuntu 20.

**Comment by matangover** [comment] 2020-09-08 19:12
OK thanks, I'll try

**Comment by matangover** [comment] 2021-02-20 20:04
Can't reproduce, closing. Please re-open if necessary. Thanks.

**Closed as completed by matangover** 2021-02-20 20:04 UTC
